# -*- coding: utf-8 -*-
"""AC 1 ARTHUR BARROS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_c49f1KlcIEeft7v0QwxsIZbs7u_vbKa

Arthur Barros 23011428
"""

import requests

RA = input("Digite o ultimo número do seu RA: ")
print(RA)

resposta = requests.get("https://api.nasa.gov/mars-photos/api/v1/rovers/spirit/photos?sol=1000&api_key=DEMO_KEY")
print(resposta)
print(resposta.json())