# -*- coding: utf-8 -*-
"""AC 1 ARTHUR BARROS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_c49f1KlcIEeft7v0QwxsIZbs7u_vbKa

Arthur Barros 23011428
"""

import requests

RA = input("Digite o ultimo número do seu RA: ")
print(RA)

print("1-Fhaz  2-Rhaz  3-Mast  4-Chemcam  5-Mahli  6-Mardi  7-Navcam  8-Pancam  9 e 0-Minites")
Robo = str(input("De acordo com o ultimo número do seu RA, qual é o seu robo? "))
Robo = Robo.lower()
print(Robo)

resposta = requests.get(f"https://api.nasa.gov/mars-photos/api/v1/rovers/spirit/photos?sol=10&camera={Robo}&api_key=DEMO_KEY")
print(resposta)
x = resposta.json()["photos"][0]["img_src"]
print("O link da imagem tirada pelo robo do seu RA é: ",  x)